# Generated by Django 4.2 on 2025-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_requestlog_alter_trackinghistory_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="request_method",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
